version: "2"

services:
  maria_db:
    image: mariadb
    container_name: wp
    environment:
      - MYSQL_ROOT_PASSWORD="mdp"

  wordpress:
    image: wordpress
    links:
      - maria_db:db
    ports:
      - 8080:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - maria_db:db
    ports:
      - 8181:80

