version: '3'
services:
    apache:
        image: httpd:2.2
        volumes:
            - "/var/www/html"
        links:
            - mysql
        ports:
            - "8080:80"
        privileged: true
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: passroot
    php: 
        build: Dockerfile/.
